### ISSUE TITLE
alugrid URL broken

### ISSUE THREAD

**Issue by psibre** [OPM/homebrew-opm#4]
Trying to install alugrid results in an error:

```
$ brew install alugrid
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/opm/homebrew-opm/alugrid.rb:7:in `<class:Alugrid>'
Please report this to the opm/opm tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/opm/homebrew-opm/alugrid.rb:7:in `<class:Alugrid>'
Please report this to the opm/opm tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/opm/homebrew-opm/alugrid.rb:7:in `<class:Alugrid>'
Please report this to the opm/opm tap!

==> Installing alugrid from opm/opm
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/opm/homebrew-opm/alugrid.rb:7:in `<class:Alugrid>'
Please report this to the opm/opm tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/opm/homebrew-opm/alugrid.rb:7:in `<class:Alugrid>'
Please report this to the opm/opm tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/opm/homebrew-opm/alugrid.rb:7:in `<class:Alugrid>'
Please report this to the opm/opm tap!

==> Downloading http://aam.mathematik.uni-freiburg.de/IAM/Research/alugrid/ALUGrid-1.52.tar.gz
==> Downloading from http://aam.uni-freiburg.de/
######################################################################## 100.0%
Warning: Calling Pathname#sha1 is deprecated!
Use Pathname#sha256 instead.
/usr/local/Library/Homebrew/extend/pathname.rb:320:in `verify_checksum'

Error: SHA1 mismatch
Expected: 3e5da3f5b88ea61dcd31f952f9dde135af634c62
Actual: 07d164fbbebe91e21ddbe316a3df3f5320acf66a
Archive: /Users/ingmar/Library/Caches/Homebrew/alugrid-1.52.tar.gz
To retry an incomplete download, remove the file above.
```

The URL redirects to a webpage, which is downloaded and misinterpreted as the source tarball:

```
$ wget http://aam.mathematik.uni-freiburg.de/IAM/Research/alugrid/ALUGrid-1.52.tar.gz
--2016-08-26 08:05:42--  http://aam.mathematik.uni-freiburg.de/IAM/Research/alugrid/ALUGrid-1.52.tar.gz
Resolving aam.mathematik.uni-freiburg.de... 132.230.12.11
Connecting to aam.mathematik.uni-freiburg.de|132.230.12.11|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://aam.uni-freiburg.de/ [following]
--2016-08-26 08:05:43--  http://aam.uni-freiburg.de/
Resolving aam.uni-freiburg.de... 132.230.1.52
Connecting to aam.uni-freiburg.de|132.230.1.52|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2016-08-26 08:05:43 ERROR 403: Forbidden.
```

The sources have been migrated to https://gitlab.dune-project.org/extensions/dune-alugrid but lacking a `1.52` tag and not knowing which commit corresponds to that version, it's hard to fix the link.

**Comment by atgeirr** [comment]
The homebrew setup is stale and has not been maintained for a long while, I am sorry if it caused you to waste time. If you are knowledgeable enough about homebrew to update it that would be very much appreciated!

**Comment by psibre** [comment]
Updating it to a more recent version of alugrid with a valid source URL would be enough IMO.

**Comment by atgeirr** [comment]
Since I don't have a useful means of testing this (without messing up my computer, I fear) I don't think I can usefully contribute. If you find a url that works, I'll merge the patch.

It seems to me that many of the versions referred to are quite old -- I am not sure how useful it will be as a base for development?

**Comment by psibre** [comment]
The only tagged release of alugrid is actually [v2.4.0](https://gitlab.dune-project.org/extensions/dune-alugrid/tags/v2.4.0).
The _good_ news is that it would be possible to update the homebrew formula for alugrid to use the source tarball from there.
The _bad_ news is that the installation procedure is fundamentally different -- it now builds with CMake, but depends on current versions of dune-common and dune-grid, so those formulas will need to be rewritten and created, respectively.
Add to that further dependencies on MPI, the duplicate, outdated superlu, and various other issues that go beyond this formula, fixing this issue _properly_ would require some [yak shaving](https://en.wiktionary.org/wiki/yak_shaving), which I'm afraid I don't have the time for.

**Comment by gcpeixoto** [comment]
Dear @psibre and @atgeirr , it seems that `alugrid.rb` still remains to be fixed to overcome the `sha256` problem. I was trying to install OPM here and I got the same error initially posted on this issue thread. 

I have solved it locally by curling the formula and generating a `sha256`, but got also the broken URL with _timeout_. Then, the URL needs to be updated as well, right? Some news?

**Comment by atgeirr** [comment]
I have not done anything about this since last time, sorry. If the dune recipes are stale, it might be necessary to start there?
